spring.application.name=normocontrol

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/normocontrol
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true